// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230105033954_Cuentaa de Paty")]
    partial class CuentaadePaty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AccountPost", b =>
                {
                    b.Property<string>("LikedPostsIDPost")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LikesIDAccount")
                        .HasColumnType("varchar(255)");

                    b.HasKey("LikedPostsIDPost", "LikesIDAccount");

                    b.HasIndex("LikesIDAccount");

                    b.ToTable("AccountPost");
                });

            modelBuilder.Entity("Models.Endpoint.Account", b =>
                {
                    b.Property<string>("IDAccount")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("IDUserRol")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RequirePasswordReset")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IDAccount");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IDUserRol");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            IDAccount = "38B9F907-5961-4589-90E8-9EC020B7D40D",
                            CreatedAt = new DateTime(2023, 1, 5, 3, 39, 54, 367, DateTimeKind.Utc).AddTicks(4565),
                            Email = "angel.g.j.reyes@gmail.com",
                            IDUserRol = "38B9F907-5961-4589-90E8-9EC020B7D40D",
                            IsVerified = true,
                            PasswordHash = "40a914448eff394e9cb44b9042f2e48c52727a49a7ff2f5062bd199014003645",
                            RequirePasswordReset = false
                        },
                        new
                        {
                            IDAccount = "701D5C1F-1243-4898-81B0-6DA7A9D29152",
                            CreatedAt = new DateTime(2023, 1, 5, 3, 39, 54, 367, DateTimeKind.Utc).AddTicks(4626),
                            Email = "paty.jaimessantos@gmail.com",
                            IDUserRol = "38B9F907-5961-4589-90E8-9EC020B7D40D",
                            IsVerified = true,
                            PasswordHash = "8b5ff0be6ed40b3c83876d4c19557c27328dc94b6ecf3fc1a57784a432191e12",
                            RequirePasswordReset = false
                        });
                });

            modelBuilder.Entity("Models.Endpoint.Comment", b =>
                {
                    b.Property<string>("IDComment")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTimeUTC")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IDAccount")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IDPost")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("IDComment");

                    b.HasIndex("IDAccount");

                    b.HasIndex("IDPost");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("Models.Endpoint.Post", b =>
                {
                    b.Property<string>("IDPost")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTimeUTC")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IDAccount")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IDPost");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("Models.Endpoint.Profile", b =>
                {
                    b.Property<string>("IDProfile")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AboutMe")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("IDAccount")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginCity")
                        .HasColumnType("longtext");

                    b.HasKey("IDProfile");

                    b.HasIndex("IDAccount");

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("Models.Endpoint.Session", b =>
                {
                    b.Property<string>("IDSession")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IDAccount")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionToken")
                        .HasColumnType("longtext");

                    b.HasKey("IDSession");

                    b.ToTable("Session", (string)null);
                });

            modelBuilder.Entity("Models.Endpoint.UserRol", b =>
                {
                    b.Property<string>("IDUserRol")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserLevel")
                        .HasColumnType("int");

                    b.Property<string>("UserRolName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserRolPermisions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IDUserRol");

                    b.ToTable("UserRol", (string)null);

                    b.HasData(
                        new
                        {
                            IDUserRol = "38B9F907-5961-4589-90E8-9EC020B7D40D",
                            UserLevel = 10,
                            UserRolName = "Voluntario",
                            UserRolPermisions = "Permiso a interactuar como voluntario en la plataformaº"
                        },
                        new
                        {
                            IDUserRol = "74F61449-AFA3-4D38-BBDE-4CE2600732D6",
                            UserLevel = 0,
                            UserRolName = "Migrante",
                            UserRolPermisions = "Permiso a interactuar como migrante en la plataformaº"
                        });
                });

            modelBuilder.Entity("AccountPost", b =>
                {
                    b.HasOne("Models.Endpoint.Post", null)
                        .WithMany()
                        .HasForeignKey("LikedPostsIDPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Endpoint.Account", null)
                        .WithMany()
                        .HasForeignKey("LikesIDAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Endpoint.Account", b =>
                {
                    b.HasOne("Models.Endpoint.UserRol", "UserRol")
                        .WithMany()
                        .HasForeignKey("IDUserRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRol");
                });

            modelBuilder.Entity("Models.Endpoint.Comment", b =>
                {
                    b.HasOne("Models.Endpoint.Account", "Account")
                        .WithMany()
                        .HasForeignKey("IDAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Endpoint.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("IDPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Models.Endpoint.Profile", b =>
                {
                    b.HasOne("Models.Endpoint.Account", "Account")
                        .WithMany()
                        .HasForeignKey("IDAccount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Models.Endpoint.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
